name: Create Release

on:
  workflow_dispatch:
  push:
    branches:
      - master  # Change this to your branch

env:
  build-number: ${GITHUB_RUN_NUMBER}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build JAR with Gradle
        run: ./gradlew build

      - name: Extract tag name
        id: extract-tag
        run: |
          # Extract the tag name from github.ref (e.g., refs/tags/v1.0.0 -> v1.0.0)
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Extracted tag name: $TAG_NAME"
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }} # GitHub automatically provides this token
        with:
          tag_name: ${{ steps.extract-tag.outputs.tag_name }} # Use the extracted tag name
          release_name: Release ${{ steps.extract-tag.outputs.tag_name }}
          draft: false
          prerelease: false

      - name: Upload JAR as Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }} # Get the upload URL from the create-release step
          asset_path: build/libs/your-jar-file.jar # Replace with the path to your JAR file
          asset_name: your-jar-file.jar # Replace with the desired name for the JAR file
          asset_content_type: application/java-archive